### ISSUE TITLE
Posting once a day is broken

### ISSUE THREAD

**Issue by Rishi556** [actifit/actifit-ios#16]
Relying on system time means that the user can easily edit the system time to make a second post in that day. Having something like a server time that the time is pulled from would make it harder for users to get around that.

**Comment by tdreid** [comment]
I have been thinking about this some.  Does there really need to be a client side limit of posting once per day @mcfarhat ? Wouldn't limiting the bot to one upvote per user per day work instead (and be harder to circumvent as @Rishi556 notes).

**Comment by Rishi556** [comment]
>  Wouldn't limiting the bot to one upvote per user per day work instead (and be harder to circumvent as @Rishi556 notes).

I like that idea.
